server:
  port: 8090
spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://10.252.3.73:8880/realms/siki
        registration:
          api-client:
            provider: keycloak
            client-id: siki-client
            client-secret: BAdQw3ubmxeJeeGXLaX8nVjescrw6n80
            scope: openid, profile, email, roles
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "gatewayserver"
    description: "Siki Gateway Server Application"
    version: "1.0.0"


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
logging:
  level:
    org.springframework.security: DEBUG