server:
  port: 8082
  servlet:
    context-path: '/products'
spring:
  application:
    name: "product"
  datasource:
    url: jdbc:mysql://localhost:3306/siki-product
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '01268797378Zx'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8880/realms/siki
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    name: "products"
    description: "Siki Product Application"
    version: "1.0.0"
payment:
  vnPay:
    url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
    tmnCode: "EDT2E52Y"
    secretKey: "VGC6H4EJ834TXE5USIHM20W3FH4469VW"
    returnUrl: "http://localhost:8090/api/products/payment/vn-pay-callback"
    version: "2.1.0"
    command: "pay"
    orderType: "other"
