server:
  port: 8085
  servlet:
    context-path: '/orders'
spring:
  application:
    name: "order"
  datasource:
    url: jdbc:mysql://localhost:3306/siki-order
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: '01268797378Zx'
#    password: '123456789'
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.55:8880/realms/siki
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    name: "orders"
    description: "Siki Order Application"
    version: "1.0.0"
