spring:
    application:
        name: payment
payment:
    vnPay:
        url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
        tmnCode: "EDT2E52Y"
        secretKey: "VGC6H4EJ834TXE5USIHM20W3FH4469VW"
        returnUrl: "http://localhost:8090/api/products/payment/vn-pay-callback"
        version: "2.1.0"
        command: "pay"
        orderType: "other"