server:
  port: 8083
  servlet:
    context-path: '/medias'
spring:
  application:
    name: "media"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8880/realms/siki
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  cloudinary:
    name: 'di6h4mtfa'
    api:
      key: '593637822396816'
      secret: 'u3aoCSJzt31lcqOJBsgykwTq81o'
info:
  app:
    name: "products"
    description: "Siki Media Application"
    version: "1.0.0"

