server:
  port: 8083

spring:
  application:
    name: "media"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8880/realms/siki
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
  app:
    name: "products"
    description: "Siki Media Application"
    version: "1.0.0"

